### ISSUE TITLE
Button only for one user.

### ISSUE THREAD

**Issue by Xmonpl** [MusaBrt/KCommando#11]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to handle buttons only for the person for whom the button was created.

**Additional context**
Easiest I think will be to solve it like this @HandleButton(customButtonId, userId)

**Comment by koply** [comment]
I think it's unnecessary feature. Because u can do it with a just one if statement. It's not a feature that the general user need.

Thank you for your opinion, I am open to any comments.
