### ISSUE TITLE
Guild-Prefix preservence

### ISSUE THREAD

**Issue by moelrobi** [MusaBrt/KCommando#6]
Hey you got a really nice and intressting project here.

Since i don't find a discord or anything else to ask you i am using this.

When using your libary, with `Integration#addCustomPrefix()`, will it saved preserved or do i need to store the prefixes somewhere and on Application Boot, set the Prefixes myself?

**Comment by koply** [comment]
Thank you! KCommando doesn't preserve the custom prefixes and blacklists. Because I didn't think it was necessary. 
I will probably add the data protection system soon. My profile has an invitation link for the Discord community. I'm owner the guild.

**Comment by moelrobi** [comment]
I would recommend you make it optional.

That way, developers may store thier entire guild settings differently and don't need to worry about a libary storing data. 👍 
Otherwise it would be a cool feature to implement! Keep up the libary! :)

**Comment by koply** [comment]
Of course there will be an optional option. I will do it as soon as possible.

**Comment by koply** [comment]
https://github.com/MusaBrt/KCommando/releases/tag/4.2.3
